[project]
name = "PythonSLM"
dynamic = ["version"]
description = "Python Package for Additive Manufacturing and 3D Printing Development"
readme = "README.rst"
license = {file = "LICENSE"}
requires-python = ">=3.8"
authors = [
    { name = "Luke Parry", email = "dev@lukeparry.uk" },
    { name = "Luktug", email = "contact@luktug.co.uk" }
]
keywords = [
    "3D Printing",
    "Additive Manufacturing",
    "AM",
    "Geometry",
    "L-PBF",
    "SLM",
    "Selective Laser Melting",
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "matplotlib",
    "networkx",
    "numpy",
    "pyclipr",
    "Rtree",
    "scikit-image",
    "scipy",
    "setuptools",
    "shapely",
    "trimesh",
]

[project.optional-dependencies]
docs = [
    "matplotlib",
    "trimesh",
    "cython",
    "jupyter",
    "networkx",
    "numpy",
    "pyclipr",
    "autodocsumm",
    "scikit-image",
    "scipy",
    "shapely",
    "sphinx",
    "sphinx-paramlinks",
    "pypandoc",
    "sphinx_rtd_theme",
    "trimesh",
]
easy = [
    "colorlog",
    "scikit-image",
    "setuptools",
    "shapely",
    "triangle",
    "trimesh",
]
support = [
    "mapbox-earcut",
    "manifold3d",
    "PyQt5",
    "setuptools",
    "shapely",
    "triangle",
    "trimesh",
    "vispy",
]

[project.urls]
Documentation = "https://pyslm.readthedocs.io/en/latest/"
Homepage = "https://github.com/drlukeparry/pyslm"
Source = "https://github.com/drylukeparry/pyslm/pyslm/"
Tracker = "https://github.com/drlukeparry/pyslm/issues"

[tool.hatch.version]
path = "pyslm/version.py"

[tool.hatch.build.targets.sdist]
include = [
    "pyslm",
]

[tool.hatch.build.targets.wheel]
include = [
    "pyslm",
]

[tool.mypy]
python_version = "3.9"
strict = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
disable_error_code = ["import-untyped", "var-annotated"]
warn_unreachable = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_defs = true
no_implicit_optional = true